// <auto-generated />
using System;
using ConsoleApp.EfSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp.EfSql.Migrations.Relationships
{
    [DbContext(typeof(RelationshipsContext))]
    [Migration("20180911004921_ForeignKey")]
    partial class ForeignKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp.EfSql.Relationships.BlogA", b =>
                {
                    b.Property<int>("BlogAId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url");

                    b.HasKey("BlogAId");

                    b.ToTable("BlogAs");
                });

            modelBuilder.Entity("ConsoleApp.EfSql.Relationships.BlogB", b =>
                {
                    b.Property<int>("BlogBId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url");

                    b.HasKey("BlogBId");

                    b.ToTable("BlogB");
                });

            modelBuilder.Entity("ConsoleApp.EfSql.Relationships.BlogC", b =>
                {
                    b.Property<int>("BlogCId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url");

                    b.HasKey("BlogCId");

                    b.ToTable("BlogCs");
                });

            modelBuilder.Entity("ConsoleApp.EfSql.Relationships.PostA", b =>
                {
                    b.Property<int>("PostAId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BlogAId");

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.HasKey("PostAId");

                    b.HasIndex("BlogAId");

                    b.ToTable("PostAs");
                });

            modelBuilder.Entity("ConsoleApp.EfSql.Relationships.PostB", b =>
                {
                    b.Property<int>("PostBId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BlogBId");

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.HasKey("PostBId");

                    b.HasIndex("BlogBId");

                    b.ToTable("PostBs");
                });

            modelBuilder.Entity("ConsoleApp.EfSql.Relationships.PostC", b =>
                {
                    b.Property<int>("PostCId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlogForeignKey");

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.HasKey("PostCId");

                    b.HasIndex("BlogForeignKey");

                    b.ToTable("PostCs");
                });

            modelBuilder.Entity("ConsoleApp.EfSql.Relationships.PostA", b =>
                {
                    b.HasOne("ConsoleApp.EfSql.Relationships.BlogA", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogAId");
                });

            modelBuilder.Entity("ConsoleApp.EfSql.Relationships.PostB", b =>
                {
                    b.HasOne("ConsoleApp.EfSql.Relationships.BlogB")
                        .WithMany("Posts")
                        .HasForeignKey("BlogBId");
                });

            modelBuilder.Entity("ConsoleApp.EfSql.Relationships.PostC", b =>
                {
                    b.HasOne("ConsoleApp.EfSql.Relationships.BlogC", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogForeignKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
