// <auto-generated />
using System;
using ConsoleApp.EfSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp.EfSql.Migrations.Relationships
{
    [DbContext(typeof(RelationshipsContext))]
    partial class RelationshipsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp.EfSql.Relationships.BlogA", b =>
                {
                    b.Property<int>("BlogAId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url");

                    b.HasKey("BlogAId");

                    b.ToTable("BlogAs");
                });

            modelBuilder.Entity("ConsoleApp.EfSql.Relationships.PostA", b =>
                {
                    b.Property<int>("PostAId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BlogAId");

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.HasKey("PostAId");

                    b.HasIndex("BlogAId");

                    b.ToTable("PostAs");
                });

            modelBuilder.Entity("ConsoleApp.EfSql.Relationships.PostA", b =>
                {
                    b.HasOne("ConsoleApp.EfSql.Relationships.BlogA", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogAId");
                });
#pragma warning restore 612, 618
        }
    }
}
